### ISSUE TITLE
Not able to install extension

### ISSUE THREAD

**Issue by vinodagarwal1990** [kotfire/vscode-php-add-property#23]
Hi I am getting error as
unable to install because, the extension '{extionsion name}' compatible with current version '1.31.0' of VS Code is not found.

My current VS code version- 
Version 1.31.0 (1.31.0)

![image](https://user-images.githubusercontent.com/55694955/86561432-41dcdf00-bf7e-11ea-8aa2-9827155f038e.png)

**Comment by kotfire** [comment]
Hello, I'm sorry you haven't been able to use the extension due to this. I'll change the minimum version required to install the extension and release a patch.

**Comment by kotfire** [comment]
Hello again,

Sadly I won't be able to release a patch for the current version. That said, I've been working for months in a rewrite of the extension to use a PHP parser and reduce the usage of RegExp along with other new features. That new version will be compatible with version 1.31.0 and above :tada: 

I'd like to launch the new version this month.

**Comment by kotfire** [comment]
Fixed in v1.0.0
