### ISSUE TITLE
Nullable property types are stripped when adding existing property

### ISSUE THREAD

**Issue by ghost** [kotfire/vscode-php-add-property#28]
Hello

Adding an existing property with a nullable PHP 7.4 to the constructor will ignore the nullable type hint:

```php
/**
 * @var string|null
 */
private ?string $blah;
```

This will result in:

```php
/**
 * Constructor.
 * @param string $blah
 */
public function __construct(string  $blah)
{
    $this->blah = $blah;
}
```

Where `$blah` is a `string` instead of a `string|null` in the docblock and a `?string` in the constructor parameter.

PS: You may also be interested in knowing that PHP 8 will support union types, so types such as these become valid as well (they may already work):

```php
private int|string $value;
```

Thanks!

**Comment by kotfire** [comment]
Added in v1.1.0
