### ISSUE TITLE
Cursor is sometimes placed in wrong location after generating property

### ISSUE THREAD

**Issue by Gert-dev** [kotfire/vscode-php-add-property#4]
Sometimes the cursor is placed in the wrong location when adding a new property. In the demo below, this happens starting from the second property that is generated, but it also sometimes happens the first time (but I can't reproduce that).

[Demo.zip](https://github.com/kotfire/vscode-php-add-property/files/3883590/Demo.zip)

(Uploaded as ZIP because GitHub won't allow WebM uploads for some reason.)

The cursor seems offset by some fixed amount of characters, as the location of the cursor inside the constructor below is also incorrect, but off by the exact same amount of characters it is off in the property itself.

**Comment by kotfire** [comment]
Can you tell me which are your indentation settings?

**Comment by Gert-dev** [comment]
Thanks for your response. I'm using spaces and four spaces as indentation.

You may be on to something there. Is it possible it is related to the indentation the cursor is currently at?

```php
class Blah
{
    /**
     * @var int
     */
    private $exstingProperty;|

    /**
     * @param int $existingProperty
     */
    public function __construct(int $existingProperty)
    {
        $this->existingProperty = $existingProperty;
    }
}
```

If I do it here (where the vertical bar is), it works. I think I can reproduce it now by starting from the above cursor position, pressing return twice (to add two newlines), causing the cursor to end up here:

```php
class Blah
{
    /**
     * @var int
     */
    private $exstingProperty;

    |
    /**
     * @param int $existingProperty
     */
    public function __construct(int $existingProperty)
    {
        $this->existingProperty = $existingProperty;
    }
}
```

... and then generate a property `test`, which then seems to cause the issue.
