### ISSUE TITLE
[feature] add support for PHP 8: Constructor property promotion

### ISSUE THREAD

**Issue by ctf0** [kotfire/vscode-php-add-property#41]
for example https://stitcher.io/blog/constructor-promotion-in-php-8

**Comment by kotfire** [comment]
I'm already working on it 👍

Feel free to add here any particular examples (code before and after) to help me test it. Thanks!

**Comment by ctf0** [comment]
// before
```php
class CustomerDTO
{
    public $name;

    public $email;

    public $birth_date;

    public function __construct(
        $name, 
        $email, 
        $birth_date
    ) {
        $this->name = $name;
        $this->email = $email;
        $this->birth_date = $birth_date;
    }
}
```

// after

```php
class CustomerDTO
{
    public function __construct(
        public $name, 
        public $email, 
        public $birth_date,
    ) {}
}
```

**Comment by kotfire** [comment]
Let me see if I understand correctly. Do you want a command to transform from classic constructor to property promotion? It is doable, what I'm working on now is support inserting/adding properties as promoted. 

// before

```php
class CustomerDTO
{
    public function __construct(
        public $name, 
        public $email
    ) {}
}
```

//after

```php
class CustomerDTO
{
    public function __construct(
        public $name, 
        public $email, 
        public $birth_date
    ) {}
}
```

**Comment by ctf0** [comment]
having the 2 options would be much appreciated, 
- a cmnd to convert current to v8 
- and a new config that tell the current cmnd of adding new props to follow the v8 flow, exactly like ur example

**Comment by kotfire** [comment]
👍
