### ISSUE TITLE
can "Remove Existing PHP Property" also remove the property setter & getter ?

### ISSUE THREAD

**Issue by ctf0** [kotfire/vscode-php-add-property#43]

**Comment by kotfire** [comment]
Sorry but I won't add this feature. This is out of the scope of the extension. The extension does not add any setter/getter and I prefer to keep it as simple as possible.

**Comment by ctf0** [comment]
yes but it does remove the property, i thought removing the setter/getter if found as well would be relevant.

**Comment by kotfire** [comment]
I understand it will be convenient, but I am not adding this feature for now.
