### ISSUE TITLE
Allow generating property without adding to constructor

### ISSUE THREAD

**Issue by Gert-dev** [kotfire/vscode-php-add-property#6]
Sometimes you want to generate properties without adding them to the constructor, i.e. they are calculated based on other values in the constructor's body or carry some other kind of state.

This could be achieved by either asking if it should be added to the constructor (which would probably be cumbersome for all other cases), or to make a separate command that skips adding it to the constructor.

A workaround is to use snippets to generate the property itself, so this isn't a sorely missing feature :-).

Thanks!

**Comment by kotfire** [comment]
I won't include this feature. It's out of the scope of the extension and can be achieved using a snippet as stated by @Gert-dev.

I prefer to not add extra complexity.
