### ISSUE TITLE
Allow selecting existing property and adding it to the constructor

### ISSUE THREAD

**Issue by Gert-dev** [kotfire/vscode-php-add-property#7]
Sometimes you have existing properties generated by some other means that aren't part of the constructor, but that you now _do_ want to make part of the constructor. In this case it would be handy to allow adding it to the constructor (i.e. via a separate command).

Since this package already carries logic for updating the constructor and even making it multi-line if it reaches the line threshold, this would be a neat feature.

Also relates to #6.

Thanks!

**Comment by kotfire** [comment]
Implemented in `0.3.0`
